apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clickhouse.service.name }}
  namespace: monitoring
  labels:
    app: {{ .Values.clickhouse.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.clickhouse.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.clickhouse.service.name }}
    spec:
      securityContext:
        runAsUser: 1100
        runAsGroup: 1100
        fsGroup: 1100
      containers:
      - name: {{ .Values.clickhouse.service.name }}
        image: {{ .Values.clickhouse.image }}
        ports:
        - containerPort: {{ .Values.clickhouse.nativePort }}
        - containerPort: {{ .Values.clickhouse.httpPort }}
        env:
        - name: CLICKHOUSE_USER
          value: {{ .Values.clickhouse.user }}
        - name: CLICKHOUSE_PASSWORD
          value: {{ .Values.clickhouse.password }}
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        - name: clickhouse-config
          mountPath: /etc/clickhouse-server/config.d/custom.xml
          subPath: config.xml
      volumes:
        - name: clickhouse-data
          persistentVolumeClaim:
            claimName: {{ .Values.clickhouse.pvcName }}
        - name: clickhouse-config
          configMap:
            name: clickhouse-config
