apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: monitoring
spec:
  storageClassName: {{ .Values.clickhouse.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
