apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clickhouse.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.clickhouse.service.type }}
  {{- if eq .Values.clickhouse.service.type "LoadBalancer" }}
  {{- if .Values.clickhouse.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.clickhouse.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  selector:
    app: {{ .Values.clickhouse.service.name }}
  ports:
  - name: client
    port: 9000
    targetPort: 9000
  - name: http
    port: 80
    targetPort: 8123
