apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.clickhouse.mcp.service.name }}
  namespace: monitoring
  labels:
    app: {{ .Values.clickhouse.mcp.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.clickhouse.mcp.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.clickhouse.mcp.service.name }}
    spec:
      containers:
      - name: clickhouse
        image: mcp/clickhouse:latest
        ports:
        - containerPort: 8000
        env:
        - name: CLICKHOUSE_USER
          value: {{ .Values.clickhouse.user }}
        - name: CLICKHOUSE_PASSWORD
          value: {{ .Values.clickhouse.password }}
        - name: CLICKHOUSE_HOST
          value: {{ .Values.clickhouse.service.name }}
        - name: CLICKHOUSE_MCP_SERVER_TRANSPORT
          value: http
        - name: CLICKHOUSE_PORT
          value: "80"
