apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-mcp
  namespace: monitoring
  labels:
    app: clickhouse-mcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-mcp
  template:
    metadata:
      labels:
        app: clickhouse-mcp
    spec:
      containers:
      - name: clickhouse
        image: mcp/clickhouse:latest
        ports:
        - containerPort: {{ .Values.clickhouse.mcp.port }}
        env:
        - name: CLICKHOUSE_USER
          value: {{ .Values.clickhouse.user }}
        - name: CLICKHOUSE_PASSWORD
          value: {{ .Values.clickhouse.password }}
        - name: CLICKHOUSE_HOST
          value: {{ .Values.clickhouse.service.name }}
        - name: CLICKHOUSE_MCP_SERVER_TRANSPORT
          value: {{ .Values.clickhouse.mcp.transport }}
