apiVersion: v1
kind: Service
metadata:
  name: clickhouse-mcp
  namespace: monitoring
spec:
  {{- if eq .Values.clickhouse.service.type "LoadBalancer" }}
  {{- if .Values.clickhouse.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.clickhouse.mcp.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  type: {{ .Values.clickhouse.mcp.service.type }}
  selector:
    app: clickhouse-mcp
  ports:
  - containerPort: 8000
    name: streamable-http
    port: 8000
    protocol: TCP
    targetPort: 8000
