apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clickhouse.mcp.service.name }}
  namespace: monitoring
spec:
  {{- if eq .Values.clickhouse.mcp.service.type "LoadBalancer" }}
  {{- if .Values.clickhouse.service.mcp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.clickhouse.mcp.service.loadBalancerIP }}
  {{- end }}
  {{- end }}
  type: {{ .Values.clickhouse.mcp.service.type }}
  selector:
    app: {{ .Values.clickhouse.mcp.service.name }}
  ports:
  - name: streamable-http
    port: 8000
    protocol: TCP
    targetPort: 8000
