apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: ingress
spec:
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:latest
  observability: null
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      zipkin: # CoreDNS
        endpoint: 0.0.0.0:9411
      syslog:
        udp:
          listen_address: "0.0.0.0:1514"
          add_attributes: true
        protocol: rfc5424

      # TODO - not used
      prometheus:
        config:
          scrape_configs:
            - job_name: 'cilium-operator'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  regex: cilium-operator
                  action: keep
            - job_name: 'envoy'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
                  regex: cilium
                  action: keep
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
                  action: keep
                  regex: 9964

    exporters:
      loadbalancing:
        routing_key: service
        protocol:
          otlp:
            tls:
              insecure: true
        resolver:
          static:
            hostnames:
              - lb-test-1:4317
              - lb-test-2:4317
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [loadbalancing]
