apiVersion: v1
kind: Service
metadata:
  name: otelcol-ingress
  namespace: monitoring
spec:
  type: LoadBalancer
  loadBalancerIP: {{.Values.ingress.ip}}
  selector:
    app: otelcol-ingress
  ports:
  - name: grpc
    port: 4317
    targetPort: 4317 
  - name: zipkin 
    port: 9411
    targetPort: 9411 
  - name: syslog
    port: 1514
    targetPort: 1514 
    protocol: UDP
